version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=django-insecure-qj)7gj7&m%-j*h^l-r-atin1eh343^))txtc)1f^h-1c&ipqlf'
      - 'DJANGO_DEBUG=True'

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"