BBBB BBBBBBB
BBBBBBBBBBBB BBBB BB BBBBBBBBBBBB
BBBB BBBB
BBBBBBBBBB BBB
 gettext(u'\n\nHello from %(site_name)s.\n\nIf you as %(user_display)s requested this email please click on the following link:\n%(activate_url)s\n\n') 

SSSSS SSSS SSSSSSSSSSSSSS

SS SSS SS SSSSSSSSSSSSSSSS SSSSSSSSS SSSS SSSSS SSSSSS SSSSS SS SSS SSSSSSSSS SSSSS
SSSSSSSSSSSSSSSS


BBBBBBBBBBBBB