# Generated by Django 4.1.3 on 2022-12-14 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
