# Generated by Django 4.1.3 on 2022-12-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fa_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
